### ISSUE TITLE
[REQUEST] Porting of the Save Editor for the localization of Yo-kai Watch 3 in Europe and North America

### ISSUE THREAD

**Issue by justin102955** [togenyan/yw_save#3]
@togenyan I am writing this to inform about the upcoming release of Yo-kai Watch 3's localization.

The first to release will be in the EU region, which is on December 7, 2018 (aka. the same day as Smash Ultimate releases on Switch.) The AU region follows the release on the next day. Though, North America will have to wait until February 8, 2019.

I would like to ask if you can port the save editor for localization of Yo-kai Watch 3; most particularly, the Yo-kai Watch 3 Save Editor that is currently in use for Sukiyaki, as the localization might be the "Definitive Edition", combining all 3 Japanese games (Sushi, Tempura, and Sukiyaki). Though, I'm a bit suspicious of how they might ax the crossover/third movie content, especially the FFXIV crossover Yo-kai, Sangokushi, and some Treasure Busters 2 content.

If by any chance you can reply to this, I'll be glad to assist you with providing information. Thank you.

**Comment by togenyan** [comment]
Thank you for letting me know about the localization.
I have a plan to update my save editor ("Yo-kai Editor 3") after EU/AU versions get released. From my experience L5 will not change save data encryption in localization, so the porting will be easy. 

> Though, I'm a bit suspicious of how they might ax the crossover/third movie content, especially the FFIXV crossover Yo-kai, Sangokushi, and some Treasure Busters 2 content.

That sounds interesting. Just curious, are Darknyan, Hovernyan and Wondernyan obtainable in non JP versions of YW2? (For JP version Wondernyan is no longer obtainable)

**Comment by justin102955** [comment]
@togenyan That, I am sure.
Meanwhile, I'm really hoping that when localization rolls into town, I hope that the "amiibo bypass" is still going to be implemented. (That is, the NFC in the Dream Medals.)

**Comment by justin102955** [comment]
> @togenyan That, I am sure.
> Meanwhile, I'm really hoping that when localization rolls into town, I hope that the "amiibo bypass" is still going to be implemented. (That is, the NFC in the Dream Medals.)
> 
> EDIT: I mixed up with the numericals, so I fixed the title. It's Final Fantasy 14, by the way.

And if this is the case, what do you hope to get out of the porting? @togenyan

**Comment by justin102955** [comment]
@togenyan I've received some grave news.

The "amiibo bypass" has been removed from the localization, and also, there's another issue I have to talk about.

so basically
this localization is an issue
**You buy the game, and the language is set to what country you bought the game from.**
So if it's from Germany, _you're stuck to German._
I'll most likely suggest the **UK edition, as that is the closest to the US version (aka, ENGLISH)**
We've never had this case before for other 3DS games. _**Why now, is YKW3 gonna be a pain in the butt to get used to...**_

**Comment by justin102955** [comment]
@togenyan News update. The localization is out now in Europe, and supposedly...

_**EVERYONE IS HERE.**_

**Comment by justin102955** [comment]
@togenyan Closing the Issue, because it's been seen via the YKW3 save editor update.
https://i.imgur.com/RMrSWRS.png
Thanks for the help, mate! By the way, PM me about the repositories just in case. 👍 
You really did a great job for the community. 🥇
